#!/bin/bash

file=graph-$1-$2-$3-$4

gnuplot -e "set terminal png; set output '$file.png'; plot '$file-0.dat' ti 'Player 0: $1:$2' with impulses, '$file-1.dat' ti 'Player1: $3:$4' with impulses"

scp $file.png R_E_D_A_C_T_E_D:/home/www/www/graphs/$1-$2-$3-$4.png